.TH PLISTUTIL 1 "October 31, 2009"
.SH NAME
plistutil \- A converter tool for binary or XML Apple property lists

.SH SYNOPSIS
.B plistutil
\-i|\-\-infile in_file.plist \-o|\-\-outfile out_file.plist [\-\-debug]

.SH OPTION
.TP
.B \-i or \-\-infile
The file to read in.
.TP
.B \-o or \-\-outfile
The file to convert to.
.TP
.B \-d, \-v or \-\-debug
Provide extended debug information.

.SH DESCRIPTION
\fBplistutil\fP 

.SH AUTHOR
plistutil was written by Zach C.
.PP
This manual page was written by Julien Lavergne <julien.lavergne@gmail.com>,
for the Debian project (but may be used by others).
